image: "mcr.microsoft.com/mssql/server:2025-latest"
saPassword: "secure_SA_password"
storage: "1Gi"
# nodePort: 31433
#databases:
# A secret with the name "<dbname>-connection" with connection details will be published
#  dbname:
#    user: "dbuser"
#    # if not defined, a random password is generated
#    password: "myFixedPassword"